import { Card, Group, Skeleton, Stack } from '@mantine/core';

export const UsePromiseSkeleton = () => {
  return (
    <Stack
      className='max-w-prose'
      gap='md'
    >
      <Card
        withBorder
        padding='lg'
        radius='md'
        shadow='sm'
      >
        <Group
          gap='md'
          mb='md'
        >
          <Skeleton
            circle
            height={80}
            width={80}
          />
          <div style={{ flex: 1 }}>
            <Skeleton
              height={28}
              mb={8}
              width='60%'
            />
            <Skeleton
              height={20}
              mb={12}
              width='40%'
            />
            <Group
              gap='xs'
              mt='xs'
            >
              <Skeleton
                height={24}
                width={60}
              />
              <Skeleton
                height={24}
                width={50}
              />
              <Skeleton
                height={24}
                width={70}
              />
            </Group>
          </div>
        </Group>

        <Stack gap='sm'>
          <div>
            <Skeleton
              height={18}
              mb={8}
              width='30%'
            />
            <Skeleton
              height={16}
              mb={4}
              width='70%'
            />
            <Skeleton
              height={16}
              width='50%'
            />
          </div>

          <div>
            <Skeleton
              height={18}
              mb={8}
              width='20%'
            />
            <Skeleton
              height={16}
              mb={4}
              width='85%'
            />
            <Skeleton
              height={16}
              width='40%'
            />
          </div>

          <div>
            <Skeleton
              height={18}
              mb={8}
              width='25%'
            />
            <Skeleton
              height={16}
              mb={4}
              width='65%'
            />
            <Skeleton
              height={16}
              width='55%'
            />
          </div>

          <div>
            <Skeleton
              height={18}
              mb={8}
              width='30%'
            />
            <Skeleton
              height={16}
              mb={4}
              width='50%'
            />
            <Skeleton
              height={16}
              mb={4}
              width='60%'
            />
            <Skeleton
              height={16}
              width='45%'
            />
          </div>
        </Stack>
      </Card>
    </Stack>
  );
};
